version: "3.9"

services:
  cocktail-app:
    build: .
    ports:
      - "8000:8000"   
      - "8501:8501"   
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data
      - ./app:/app/app
